[package]
name = "wormod"
version = "1.0.0"
authors = ["Valentino Orlandi <valentinox@disroot.org>"]

edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
regex = "1.11.1"
sysinfo = "0.32.0"
